CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Admins" (
    "AdminId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" integer NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(512) NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("AdminId")
);

CREATE TABLE "Clients" (
    "ClientId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" integer NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(512) NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("ClientId")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Admins_username" ON "Admins" (username);

CREATE UNIQUE INDEX "IX_Clients_username" ON "Clients" (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510165804_InitialPostgresSchema', '8.0.4');

COMMIT;

